[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
saguaro_gatekeeper = "DApD5AGWB5TcN83q3NRGGdQtWa3i7w1W7rVUzsvFLBqe"

[programs.localnet]
saguaro_gatekeeper = "DApD5AGWB5TcN83q3NRGGdQtWa3i7w1W7rVUzsvFLBqe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
